### ISSUE TITLE
Question: is this proxy stable?

### ISSUE THREAD

**Issue by derrickburns** [mpihlak/mongoproxy#2]
I need a mongo proxy that works with the 3.6+ wire protocol.  My primary need is to intercept write requests and return success while letting read requests through. 

Is this proxy a good place to start?  If not, do you know of others?

**Comment by mpihlak** [comment]
The proxy is very stable and would be a good start **if** you only want to take a peek of the data. If, however you need to change the packets then that’s going to be much more involved as  I’ve deliberately avoided changing the data stream so that I can keep it simple.

**Comment by derrickburns** [comment]
Thank you! Nice work!
