### ISSUE TITLE
Service mesh integration

### ISSUE THREAD

**Issue by derrickburns** [mpihlak/mongoproxy#3]
I use linkerd and it uses Sidecars with iptables. I want to use your proxy in that environment. I can figure it out myself, but if you already have a config that avoids conflicts I would appreciate it.

**Comment by mpihlak** [comment]
For linkerd deployment I'm setting `--outbound-ports-to-ignore 27017` so that it skips MongoDb traffic. Another approach is described in https://linkerd.io/2/features/protocol-detection
