### ISSUE TITLE
Support outbound TLS encryption.

### ISSUE THREAD

**Issue by derrickburns** [mpihlak/mongoproxy#4]
Since your proxy inspects the traffic, the traffic  obviously cannot be encrypted. That is fine for me if I deploy the proxy as a sidecar.

However, my application must be HIPAA compliant. So, I need to encrypt the traffic when it leaves the proxy.  

At present, it appears that the proxy does not support  outbound TLS encryption.  Any plans to support it?

**Comment by mpihlak** [comment]
I haven't given TLS any thought at the moment. Though it looks like that would be fairly involved and take more time than I could contribute to a hobby project. Maybe using an external TLS proxy (like `stunnel`) would be an option?

**Comment by mpihlak** [comment]
Closing this, as TLS support is not on the horizon.
